# Generated by Django 3.0.3 on 2020-05-31 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WIDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.IntegerField(choices=[(1, 'Process Document'), (2, 'Work Instruction'), (3, 'Check Board'), (4, 'Form'), (9, 'Others')], default=2)),
                ('doc_number', models.CharField(max_length=30)),
                ('doc_name', models.CharField(max_length=255)),
                ('doc_version', models.IntegerField()),
                ('doc_date', models.DateField()),
                ('doc_attachment', models.FileField(upload_to='work_instruction')),
            ],
            options={
                'ordering': ['doc_number'],
            },
        ),
        migrations.CreateModel(
            name='WIDoc_Revise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_revision', models.IntegerField()),
                ('doc_modify', models.TextField()),
                ('doc_revisor', models.CharField(max_length=100)),
                ('doc_rev_date', models.DateField()),
                ('doc_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_f', to='work_instruction.WIDoc')),
            ],
        ),
    ]
