# Generated by Django 3.0.3 on 2020-07-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_instruction', '0003_auto_20200531_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widoc',
            options={'ordering': ['doc_type', 'doc_number']},
        ),
    ]
