# Generated by Django 3.0.3 on 2020-07-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reference_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
