# Generated by Django 3.0.3 on 2020-07-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.IntegerField(choices=[(1, 'Po Processing'), (2, 'Material Delivering'), (3, 'In Stock'), (4, 'On Process'), (5, 'Finished'), (6, 'Paused'), (7, 'Cancelled'), (8, 'Other')], null=True),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
