# Generated by Django 3.0.3 on 2020-05-27 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Solved'), (2, 'Unsolved'), (3, 'Urgent')], default=2)),
                ('title', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-status', '-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyer', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='problem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Reply_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('replyattach', models.FileField(upload_to='problem/reply')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('reply_father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_f', to='problem.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('postattach', models.ImageField(upload_to='problem/post/')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('post_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_f', to='problem.Post')),
            ],
        ),
    ]
