# Generated by Django 3.2.3 on 2022-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20200526_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Work'), (2, 'Study'), (3, 'Life')], default=3),
        ),
    ]
